import React from 'react';
import styled from 'styled-components';
import tsIcon from '../../assets/icons/ts.svg';
import vueJs from '../../assets/icons/vuejs.svg';
import reactJs from '../../assets/icons/reactjs.svg';
import threeJs from '../../assets/icons/threejs.png';
import html5 from '../../assets/icons/html5.svg';
import css3 from '../../assets/icons/css3.svg';
import sass from '../../assets/icons/sass.svg';
import jest from '../../assets/icons/jest.png';
import microsoft from '../../assets/icons/microsoft.svg';
import azuredevops from '../../assets/icons/azuredevops.png';
import graphql from '../../assets/icons/graphql.svg';
import mysql from '../../assets/icons/mysql.svg';
import microsoftsql from '../../assets/icons/microsoftsql.svg';
import postman from '../../assets/icons/postman.png';
import kafka from '../../assets/icons/kafka.png';

const TechStackContainer = styled.div`
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    align-items: center;
    height: 55vh;
    overflow-x: auto;
`;

const TechStackItem = styled.a`
    font-size: 1rem;
    padding: 1.5rem;
`;

const IMG = styled.img`
    width: 5rem;
`;

export default function TechStack() {
    return (
        <TechStackContainer>
            <p align="left">
                <TechStackItem
                    href="https://reactjs.org/"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://raw.githubusercontent.com/devicons/devicon/master/icons/react/react-original-wordmark.svg"
                        alt="react"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://vuejs.org/"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://raw.githubusercontent.com/devicons/devicon/master/icons/vuejs/vuejs-original-wordmark.svg"
                        alt="vuejs"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://angular.io"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://angular.io/assets/images/logos/angular/angular.svg"
                        alt="angular"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://www.mongodb.com/"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://raw.githubusercontent.com/devicons/devicon/master/icons/mongodb/mongodb-original-wordmark.svg"
                        alt="mongodb"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://www.microsoft.com/en-us/sql-server"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://www.svgrepo.com/show/303229/microsoft-sql-server-logo.svg"
                        alt="mssql"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://www.mysql.com/"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://raw.githubusercontent.com/devicons/devicon/master/icons/mysql/mysql-original-wordmark.svg"
                        alt="mysql"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://developer.android.com"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://raw.githubusercontent.com/devicons/devicon/master/icons/android/android-original-wordmark.svg"
                        alt="android"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://www.arduino.cc/"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://cdn.worldvectorlogo.com/logos/arduino-1.svg"
                        alt="arduino"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://azure.microsoft.com/en-in/"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://www.vectorlogo.zone/logos/microsoft_azure/microsoft_azure-icon.svg"
                        alt="azure"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://babeljs.io/"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://www.vectorlogo.zone/logos/babeljs/babeljs-icon.svg"
                        alt="babel"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://www.gnu.org/software/bash/"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://www.vectorlogo.zone/logos/gnu_bash/gnu_bash-icon.svg"
                        alt="bash"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://www.blender.org/"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://download.blender.org/branding/community/blender_community_badge_white.svg"
                        alt="blender"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://getbootstrap.com"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://raw.githubusercontent.com/devicons/devicon/master/icons/bootstrap/bootstrap-plain-wordmark.svg"
                        alt="bootstrap"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://www.cprogramming.com/"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://raw.githubusercontent.com/devicons/devicon/master/icons/c/c-original.svg"
                        alt="c"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://www.chartjs.org"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://www.chartjs.org/media/logo-title.svg"
                        alt="chartjs"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://www.w3schools.com/cpp/"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://raw.githubusercontent.com/devicons/devicon/master/icons/cplusplus/cplusplus-original.svg"
                        alt="cplusplus"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://www.w3schools.com/cs/"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://raw.githubusercontent.com/devicons/devicon/master/icons/csharp/csharp-original.svg"
                        alt="csharp"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://www.w3schools.com/css/"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://raw.githubusercontent.com/devicons/devicon/master/icons/css3/css3-original-wordmark.svg"
                        alt="css3"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://www.cypress.io"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://raw.githubusercontent.com/simple-icons/simple-icons/6e46ec1fc23b60c8fd0d2f2ff46db82e16dbd75f/icons/cypress.svg"
                        alt="cypress"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://www.docker.com/"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://raw.githubusercontent.com/devicons/devicon/master/icons/docker/docker-original-wordmark.svg"
                        alt="docker"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://dotnet.microsoft.com/"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://raw.githubusercontent.com/devicons/devicon/master/icons/dot-net/dot-net-original-wordmark.svg"
                        alt="dotnet"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://www.electronjs.org"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://raw.githubusercontent.com/devicons/devicon/master/icons/electron/electron-original.svg"
                        alt="electron"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://expressjs.com"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://raw.githubusercontent.com/devicons/devicon/master/icons/express/express-original-wordmark.svg"
                        alt="express"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://www.figma.com/"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://www.vectorlogo.zone/logos/figma/figma-icon.svg"
                        alt="figma"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://git-scm.com/"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://www.vectorlogo.zone/logos/git-scm/git-scm-icon.svg"
                        alt="git"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://grafana.com"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://www.vectorlogo.zone/logos/grafana/grafana-icon.svg"
                        alt="grafana"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://graphql.org"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://www.vectorlogo.zone/logos/graphql/graphql-icon.svg"
                        alt="graphql"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://www.w3.org/html/"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original-wordmark.svg"
                        alt="html5"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://developer.mozilla.org/en-US/docs/Web/JavaScript"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-original.svg"
                        alt="javascript"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://kafka.apache.org/"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://www.vectorlogo.zone/logos/apache_kafka/apache_kafka-icon.svg"
                        alt="kafka"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://kotlinlang.org"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://www.vectorlogo.zone/logos/kotlinlang/kotlinlang-icon.svg"
                        alt="kotlin"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://www.linux.org/"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://raw.githubusercontent.com/devicons/devicon/master/icons/linux/linux-original.svg"
                        alt="linux"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://nestjs.com/"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://raw.githubusercontent.com/devicons/devicon/master/icons/nestjs/nestjs-plain.svg"
                        alt="nestjs"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://www.nginx.com"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://raw.githubusercontent.com/devicons/devicon/master/icons/nginx/nginx-original.svg"
                        alt="nginx"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://nodejs.org"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://raw.githubusercontent.com/devicons/devicon/master/icons/nodejs/nodejs-original-wordmark.svg"
                        alt="nodejs"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://www.oracle.com/"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://raw.githubusercontent.com/devicons/devicon/master/icons/oracle/oracle-original.svg"
                        alt="oracle"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://postman.com"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://www.vectorlogo.zone/logos/getpostman/getpostman-icon.svg"
                        alt="postman"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://www.python.org"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://raw.githubusercontent.com/devicons/devicon/master/icons/python/python-original.svg"
                        alt="python"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://redux.js.org"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://raw.githubusercontent.com/devicons/devicon/master/icons/redux/redux-original.svg"
                        alt="redux"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://sass-lang.com"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://raw.githubusercontent.com/devicons/devicon/master/icons/sass/sass-original.svg"
                        alt="sass"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://www.selenium.dev"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://raw.githubusercontent.com/detain/svg-logos/780f25886640cef088af994181646db2f6b1a3f8/svg/selenium-logo.svg"
                        alt="selenium"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://www.sqlite.org/"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://www.vectorlogo.zone/logos/sqlite/sqlite-icon.svg"
                        alt="sqlite"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://developer.apple.com/swift/"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://raw.githubusercontent.com/devicons/devicon/master/icons/swift/swift-original.svg"
                        alt="swift"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://tailwindcss.com/"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://www.vectorlogo.zone/logos/tailwindcss/tailwindcss-icon.svg"
                        alt="tailwind"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://www.tensorflow.org"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://www.vectorlogo.zone/logos/tensorflow/tensorflow-icon.svg"
                        alt="tensorflow"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://www.typescriptlang.org/"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://raw.githubusercontent.com/devicons/devicon/master/icons/typescript/typescript-original.svg"
                        alt="typescript"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://vuetifyjs.com/en/"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://bestofjs.org/logos/vuetify.svg"
                        alt="vuetify"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://webpack.js.org"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://raw.githubusercontent.com/devicons/devicon/d00d0969292a6569d45b06d3f350f463a0107b0d/icons/webpack/webpack-original-wordmark.svg"
                        alt="webpack"
                    />
                </TechStackItem>
                <TechStackItem
                    href="https://www.adobe.com/products/xd.html"
                    target="_blank"
                    rel="noreferrer"
                >
                    <IMG
                        src="https://cdn.worldvectorlogo.com/logos/adobe-xd.svg"
                        alt="xd"
                    />
                </TechStackItem>
            </p>
        </TechStackContainer>
    );
}
